version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.prod
    container_name: todo-Docker
    ports:
      - "8080:3000"
    volumes:
      - /app/node_modules
      - .:/app:cached
    depends_on:
      - mongo
    restart: unless-stopped

  mongo:
    image: mongo:latest
    restart: unless-stopped

    container_name: mongodb
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
