# Use Node Alpine for smaller image
FROM node:18-alpine

# Set working directory
WORKDIR /app

# Install dependencies
COPY package.json package-lock.json ./
RUN npm install

# Copy source files
COPY . .

# Expose default Next.js dev port
EXPOSE 3000

# Start development server
CMD ["npm", "run", "dev"]
